{
 "title": "System Status",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Project Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Taiga",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: \"taiga\"",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Jira",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: jira",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Confluence",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: confluence",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Average Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "heartbeat_monitor_duration_us",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "beats_type: heartbeat AND (source: confluence OR source: jira OR source: taiga)",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Deliverables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "DTS Home",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: \"dts home\"",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Canteen",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: canteen",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "My EI",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: \"my ei\"",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Average Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "heartbeat_monitor_duration_us",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "beats_type: heartbeat AND (source: \"dts home\" OR source: canteen source: \"my ei\")",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Infrastructure and ALM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Helm Repo",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: helm",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: \"jenkins\"",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "status",
     "bucketAggs": [
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "metrics": [
      {
       "field": "number_status",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "_exists_: heartbeat_monitor_status AND source: \"grafana\"",
     "timeField": "timestamp",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Average Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Response Time (ms)" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "source",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "heartbeat_monitor_duration_us",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "avg"
      }
     ],
     "query": "beats_type: heartbeat AND (source: \"helm\" OR source: jenkins OR source: \"grafana\")",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}