# Module: windows
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.4/metricbeat-module-windows.html

- module: windows
  metricsets: [service]
  period: 10s

- module: windows
  metricsets: [perfmon]
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.time.total.pct
      query: '\Processor Information(_Total)\% Processor Time'

    # - instance_label: physical_disk.name
    #   measurement_label: physical_disk.write.per_sec
    #   query: '\PhysicalDisk(*)\Disk Writes/sec'

    # - instance_label: physical_disk.name
    #   measurement_label: physical_disk.write.time.pct
    #   query: '\PhysicalDisk(*)\% Disk Write Time'
